package bpos.common.model.Validators.Enums;

public enum ValidatorStrategy {
    ADDRESS,BLOODTEST,CENTER,COUPON,DONATION,DONATIONTYPE,EVENT,INSTITUTION,LOGINFO,MEDICALINFO,PERSON,PERSONALDATA,RETRIEVEDCOUPONS,STUDENT
}
